// @ts-nocheck
import {useState,useEffect,useRef} from 'react';
import {MobileScroll,BottomSheet,KeyboardInput,useKeyboard} from './mobile';
import {House,Hand,Gear,User,Play,ChartBar,CaretRight,CaretLeft,DotsThree,Circle,Check,SpeakerHigh,ArrowClockwise,Lightbulb,FileText,FlowerLotus,Clock,Bluetooth,Info,ArrowRight,Waveform,CheckCircle} from '@phosphor-icons/react';
import {useStudio,action,API,ART,names,fmt,date,connectBLE} from './studio';
const titles={home:'非遗之手',device:'我的设备',calibrate:'手套校准',training:'动作练习',report:'学习报告',history:'我的学习',gestures:'手势管理'};
export default function Prototype(){
 const [s,error]=useStudio('mobile'),[page,setPage]=useState('home'),[sheet,setSheet]=useState(''),[toast,setToast]=useState(''),[busy,setBusy]=useState(false),[selectedReport,setReport]=useState(null),[video,setVideo]=useState(0),[config,setConfig]=useState({learner:'',serviceUUID:'',notifyUUID:'',writeUUID:''}),[gesture,setGesture]=useState({name:'',kind:'correct',tolerance:100});const keyboard=useKeyboard();
 const lastFeedback=useRef('');
 useEffect(()=>{const key=s?.feedback?.kind||'';if(key==='match'&&lastFeedback.current!==key&&s?.session&&!s.session.paused&&s.settings.voice&&'speechSynthesis' in window){const u=new SpeechSynthesisUtterance('姿态匹配，请保持动作连贯');u.lang='zh-CN';speechSynthesis.speak(u);}lastFeedback.current=key;},[s]);
 const go=p=>{keyboard.hide();setPage(p);};
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);}},[toast]);
 const run=async f=>{if(busy)return;setBusy(true);try{return await f();}catch(e){setToast(e.message);}finally{setBusy(false);}};
 const act=(t,p)=>run(()=>action(t,p));
 if(!s)return <div className="m-loading"><FlowerLotus size={45}/><h1>非遗之手</h1><p>{error||'正在打开你的陶艺空间…'}</p></div>;
 const connected=s.device.connected,cal=s.calibration,rep=selectedReport||s.reports[0],tab=['home','device','history'].includes(page),activeTab=['device','calibrate','gestures'].includes(page)?'device':page==='history'?'history':'home';
 const start=()=>run(async()=>{if(!s.session)await action('start');go('training');});
 const finish=()=>run(async()=>{const r=await action('finish');setReport(r);go('report');});
 const settings=()=>{setConfig({...s.settings});setSheet('settings');};
 const bars=(compact=false)=><div className={'m-bars '+(compact?'compact':'')}>{names.map((n,i)=><div key={n}><div className="m-track"><span style={{height:connected?`${Math.min(100,(s.device.values?.[i]||0)/30)}%`:'0%'}}/></div><small>{n}</small></div>)}</div>;
 const row=(label,Icon,fn,sub=null)=><button className="m-row" onClick={fn}><Icon size={24}/><span>{label}{sub&&<small>{sub}</small>}</span><CaretRight size={17}/></button>;
 const records=(limit=20)=>s.reports.slice(0,limit).map(r=><button className="m-record" key={r.id} onClick={()=>{setReport(r);go('report');}}><img src={ART+'pottery-hands.png'} alt="揉泥练习"/><span><b>{r.lesson}</b><small>{date(r.startedAt)} · {fmt(r.duration)}</small></span><CaretRight size={16}/></button>);
 return <div className="pottery-mobile">
 <header className={'m-header '+(page==='home'?'home':'')}>
 {page!=='home'&&page!=='device'&&page!=='history'&&<button aria-label="返回" onClick={()=>go(page==='calibrate'||page==='gestures'?'device':'home')}><CaretLeft size={23}/></button>}
 <h1>{titles[page]}</h1><button className="m-capsule" aria-label="更多操作" onClick={()=>setSheet('menu')}><DotsThree size={23} weight="bold"/><i/><Circle size={16}/></button>
 </header>
 <div className={'m-scroll-area '+(tab?'has-tabs':'')}><MobileScroll key={page} className="m-scroll"><main className={'m-content '+page}>
 {error&&<p className="m-note">{error}</p>}
 {page==='home'&&<><p className="m-greeting">从一次揉泥开始</p><section className="m-hero"><img src={ART+'pottery-hands.png'} alt="双手揉泥，感受陶土的质感"/><div className="m-hero-copy"><h2>揉泥基础</h2><p>观察手法，感受节奏</p><button className="m-primary" onClick={()=>go('training')}>开始学习<ArrowRight size={18}/></button></div></section><button className="m-device-strip" onClick={()=>go('device')}><img src={ART+'glove-open.png'} alt="陶艺手套"/><span><b>我的手套</b><small><i className={connected?'dot green':'dot'}/>{connected?'已连接':'待连接'}</small></span><CaretRight/></button><h3>练习路径</h3><div className="m-path"><button onClick={()=>{go('training');}}><span><Play weight="fill"/></span><b>观看示范</b><small>学习规范动作</small></button><CaretRight size={14}/><button onClick={()=>go('calibrate')}><span><Gear weight="fill"/></span><b>校准手套</b><small>适配你的手型</small></button><CaretRight size={14}/><button onClick={start}><span><ChartBar weight="fill"/></span><b>开始练习</b><small>实时动作指导</small></button></div><h3>最近练习</h3>{s.reports.length?records(1):<div className="m-empty-small"><p>从今天起，留下你的练习足迹</p><button onClick={start}>开始第一次练习<ArrowRight size={15}/></button></div>}</>}
 {page==='device'&&<><p className="m-muted">电脑主机：{s.hardware?.connected?'串口已打开':'尚未连接'} · {s.hardware?.sampleFresh?'采样更新中':s.hardware?.mode===1?'识别模式无连续采样':'等待数据'}</p><section className="m-glove-card"><img src={ART+'glove-open.png'} alt="陶艺手套"/><div><h2>陶艺手套</h2><p><i className={connected?'dot green':'dot'}/>{connected?'已连接':'待连接'}</p><small>{connected?'数据接收正常':'准备好，让动作被看见'}</small></div></section><section className="m-card"><h3>手指状态</h3>{bars()}</section><div className="m-list">{row('手套校准',Gear,()=>go('calibrate'),cal?.completed?'已完成个人校准':null)}{row('手势管理',Hand,()=>go('gestures'))}<button className="m-row" onClick={()=>act('settings',{voice:!s.settings.voice})}><SpeakerHigh size={24}/><span>语音提示</span><span className={'m-switch '+(s.settings.voice?'on':'')}/></button></div>{connected?<button className="m-outline disconnect" onClick={()=>act('disconnect')}>断开连接</button>:<button className="m-primary" disabled={busy} onClick={()=>run(async()=>{setToast(s.hardware?.connected?'电脑主机手套已连接':'请先在电脑工作台的真实手套面板连接设备');})}><Bluetooth/>查看电脑连接</button>}<button className="m-text" onClick={settings}>连接设置</button></>}
 {page==='calibrate'&&<><div className="m-stepper"><span className="done"><Check/><small>佩戴检查</small></span><i/><span className={!cal?.completed?'current':'done'}>2<small>握拳</small></span><i/><span className={cal?.completed?'done':''}>3<small>张开</small></span></div><img className="m-calibration-image" src={ART+(cal?.fist&&!cal.completed?'glove-open.png':'glove-fist.png')} alt="个人校准动作"/><h2 className="m-center">{cal?.completed?'校准完成，准备练习':cal?.fist?'张开五指，保持稳定':'轻轻握拳，保持稳定'}</h2><p className="m-center m-muted">让手套适应你的手型</p>{bars(true)}<button className="m-primary" disabled={busy} onClick={()=>run(async()=>{if(cal?.completed){go('gestures');return;}await action('calibrate',{step:cal?.fist?'open':'fist'});setToast('姿态已采集');})}>{cal?.completed?'管理参考手势':cal?.fist?'采集张开姿态':'采集握拳姿态'}</button><button className="m-outline" onClick={()=>act('calibrate',{step:'fist'})}>重新采集握拳</button></>}
 {page==='training'&&<><div className="m-training-title"><h3>揉泥基础</h3><strong>{fmt(s.session?.elapsed)}</strong></div><video className="m-video" key={video} src={API+`/media/lesson-${video}.mp4`} poster={ART+'pottery-hands.png'} controls playsInline preload="metadata"/><div className="m-video-tabs">{['正面示范','侧面示范','近景示范'].map((v,i)=><button key={v} className={i===video?'active':''} onClick={()=>setVideo(i)}>{v}</button>)}</div><section className="m-card m-feedback"><h2>{s.session?s.feedback.text:'观察手法，准备练习'}</h2><p>{s.feedback.kind==='match'?'手指状态与参考姿态接近':connected?'按自己的节奏，慢慢找到熟悉的感觉':'观看示范，也可以先记录自主练习'}</p>{bars(true)}</section><div className="m-progress"><span className="active"><CheckCircle/>准备</span><span className={s.session?'active':''}><Play/>练习</span><span><Circle/>完成</span></div><div className="m-bottom-actions">{s.session?<><button className="m-outline" onClick={()=>act(s.session.paused?'resume':'pause')}>{s.session.paused?'继续':'暂停'}</button><button className="m-primary" disabled={busy} onClick={finish}>结束练习</button></>:<button className="m-primary" disabled={busy} onClick={start}>开始练习</button>}</div></>}
 {page==='report'&&rep&&<><div className="m-report-lesson"><img src={ART+'pottery-hands.png'} alt="揉泥"/><span><h3>{rep.lesson}</h3><small>{date(rep.startedAt)}</small></span></div><h2 className="m-report-heading">这一次，更从容</h2><div className="m-stats"><div><small>练习时长</small><b>{fmt(rep.duration)}</b></div><div><small>采集帧数</small><b>{rep.sampleCount}<em> 帧</em></b></div><div><small>姿态匹配</small><b>{rep.sampleCount?rep.matches:'—'}<em> 次</em></b></div></div><section className="m-card"><h3>姿态匹配记录</h3>{rep.sampleCount?<><div className="m-timeline">{rep.timeline.map((p,i)=><i key={i} className={p.matched?'match':'adjust'}/>)}</div><div className="m-axis"><span>0:00</span><span>{fmt(rep.duration)}</span></div></>:<p className="m-note">本次未采集手套数据，已保存自主练习时长。</p>}</section><section className="m-card m-advice"><h3>练习建议</h3><p><Lightbulb/>先放慢节奏，再保持连贯</p><p><FileText/>重新佩戴手套后，记得校准</p></section><div className="m-bottom-actions"><button className="m-primary" onClick={()=>go('training')}>再练一次</button><button className="m-outline" onClick={()=>go('history')}>查看历史</button></div></>}
 {page==='history'&&<><button className="m-profile" onClick={settings}><span className="m-avatar"><User size={31} weight="duotone"/></span><span><h2>{s.settings.learner}</h2><small>在手与泥土之间，遇见更好的自己</small></span><CaretRight size={17}/></button><section className="m-card"><div className="m-section-head"><h3>近7日练习</h3><small>{s.reports.filter(r=>r.startedAt>=new Date(new Date().setHours(0,0,0,0)).getTime()-6*86400000).length}次</small></div><div className="m-week">{Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const count=s.reports.filter(r=>new Date(r.startedAt).toDateString()===d.toDateString()).length;return <div key={i}><span style={{height:Math.max(3,Math.min(50,count*12))}}/><small>{['日','一','二','三','四','五','六'][d.getDay()]}</small></div>;})}</div></section><h3>练习记录</h3>{s.reports.length?<div className="m-records">{records()}</div>:<div className="m-empty-small"><FileText size={35}/><p>每一次练习，都值得留下</p><button onClick={()=>go('training')}>开始第一次练习</button></div>}<div className="m-list">{row('个人校准',Gear,()=>go('calibrate'))}{row('语音设置',SpeakerHigh,settings)}</div></>}
 {page==='gestures'&&<><p className="m-muted">保持一个清晰的动作，将它留作练习参考。</p>{s.templates.length?s.templates.map(t=><article className="m-card m-gesture" key={t.id}><Hand size={30}/><div><h3>{t.name}</h3><small>{t.kind==='correct'?'正确姿态':'待纠正姿态'} · 容差 {t.tolerance}</small></div></article>):<div className="m-empty-small"><Hand size={45}/><h3>留下第一个参考姿态</h3><p>连接手套，保持姿态后录入。</p></div>}<button className="m-primary" onClick={()=>{setGesture({name:'',kind:'correct',tolerance:s.settings.tolerance});setSheet('gesture');}}>录入手势</button></>}
 </main></MobileScroll></div>
 {tab&&<nav className="m-tabs">{[['home','学习',House],['device','设备',Hand],['history','我的',User]].map(([id,label,Icon])=><button key={id} className={activeTab===id?'active':''} onClick={()=>go(id)}><Icon size={24} weight={activeTab===id?'fill':'regular'}/><span>{label}</span></button>)}</nav>}
 {toast&&<div className="m-toast" role="status">{toast}</div>}
 <BottomSheet open={!!sheet} onOpenChange={open=>!open&&setSheet('')} title={sheet==='settings'?'个人与连接设置':sheet==='gesture'?'录入参考手势':'更多操作'}><div className="m-sheet-content">
 {sheet==='menu'&&<>{row('个人设置',Gear,settings)}{row('我的设备',Hand,()=>{setSheet('');go('device');})}{row('练习记录',FileText,()=>{setSheet('');go('history');})}<p className="m-muted">非遗之手 · 陶艺学习与动作指导</p></>}
 {sheet==='settings'&&<>{[['learner','学习者名称'],['serviceUUID','蓝牙服务 UUID'],['notifyUUID','通知特征 UUID'],['writeUUID','写入特征 UUID']].map(([key,label])=><label className="m-field" key={key}>{label}<KeyboardInput value={config[key]} onChange={e=>setConfig({...config,[key]:e.target.value})} onBlur={()=>keyboard.hide()} placeholder={key==='learner'?'你的称呼':'填写设备提供的 UUID'}/></label>)}<button className="m-primary" onClick={()=>run(async()=>{await action('settings',config);setSheet('');setToast('设置已保存');})}>保存设置</button></>}
 {sheet==='gesture'&&<><label className="m-field">手势名称<KeyboardInput value={gesture.name} onChange={e=>setGesture({...gesture,name:e.target.value})} onBlur={()=>keyboard.hide()} placeholder="例如 揉泥准备姿态"/></label><div className="m-choice"><button className={gesture.kind==='correct'?'selected':''} onClick={()=>setGesture({...gesture,kind:'correct'})}>正确姿态</button><button className={gesture.kind==='incorrect'?'selected':''} onClick={()=>setGesture({...gesture,kind:'incorrect'})}>待纠正姿态</button></div><label className="m-field">匹配容差<KeyboardInput type="number" value={gesture.tolerance} onChange={e=>setGesture({...gesture,tolerance:Number(e.target.value)})} onBlur={()=>keyboard.hide()}/></label><button className="m-primary" onClick={()=>run(async()=>{await action('template',gesture);setSheet('');setToast('参考手势已保存');})}>采集并保存</button></>}
 </div></BottomSheet>
 </div>;
}

