import {CalibrationDialog} from './CalibrationDialog';
import {HardwarePanel} from './HardwarePanel';
import {useState,useEffect,useRef} from 'react';
import {House,SlidersHorizontal,Hand,ChartBar,Gear,UserCircle,Question,ArrowRight,DownloadSimple,Clock,Play,Check,SpeakerHigh,ArrowClockwise,PlugsConnected,FlowerLotus,CaretRight,X,FileText,Trash,UploadSimple,Lightbulb,Info,Bluetooth,DeviceMobile,Waveform,CheckCircle} from '@phosphor-icons/react';
import SensorChart from './Chart';
import {useStudio,action,API,ART,names,colors,fmt,date,download,connectSerial,connectBLE,disconnect,sendCommand,request,parseValues} from './studio';
const sections=[['work','训练工作台',House],['device','设备与校准',SlidersHorizontal],['gestures','手势管理',Hand],['history','学习记录',ChartBar],['settings','设置',Gear]];
const Badge=({active,children})=><span className={'badge '+(active?'active':'')}><i/>{children}</span>;
export function App(){
 const [calibrationOpen,setCalibrationOpen]=useState(false);
 const [s,error]=useStudio('desktop'),[page,setPage]=useState('work'),[toast,setToast]=useState(''),[modal,setModal]=useState(null),[busy,setBusy]=useState(false),[report,setReport]=useState(null),[range,setRange]=useState(20),[search,setSearch]=useState('');
 const [form,setForm]=useState({name:'',kind:'correct',tolerance:100}),[settings,setSettings]=useState(null),[cmd,setCmd]=useState(''),[videoIndex,setVideoIndex]=useState(0);const inputRef=useRef(),replayRef=useRef(null),lastFeedback=useRef('');
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);}},[toast]);
 useEffect(()=>{if(s&&!settings)setSettings({...s.settings});},[s]);
 useEffect(()=>()=>clearInterval(replayRef.current),[]);
 useEffect(()=>{if(s?.settings.voice&&s.session&&!s.session.paused&&s.feedback.kind==='match'&&lastFeedback.current!=='match'&&'speechSynthesis' in window){const u=new SpeechSynthesisUtterance('姿态匹配，请保持');u.lang='zh-CN';speechSynthesis.cancel();speechSynthesis.speak(u);}lastFeedback.current=s?.feedback.kind;},[s?.feedback.kind,s?.session?.paused]);
 const run=async(fn)=>{if(busy)return;setBusy(true);try{return await fn();}catch(e){setToast(e.message);}finally{setBusy(false);}};
 const act=(t,p,notice)=>run(async()=>{const r=await action(t,p);if(notice)setToast(notice);return r;});
 const finish=()=>run(async()=>{const r=await action('finish');clearInterval(replayRef.current);setReport(r);setModal('report');});
 const openSettings=()=>{setSettings({...s.settings});setPage('settings');};
 if(!s)return <div className="loading"><FlowerLotus size={48}/><h1>非遗之手</h1><p>{error||'正在打开陶艺教学工作台…'}</p>{error&&<button onClick={()=>location.reload()}>重新连接</button>}</div>;
 const calibrated=s.calibration?.completed,connected=s.device.connected,feed=s.feedback;
 const csv=()=>download('手指数据.csv','时间,拇指,食指,中指,无名指,小指\n'+s.samples.map(x=>[x.elapsed,...x.values].join(',')).join('\n'),'text/csv;charset=utf-8');
 const readings=<div className="readings">{names.map((n,i)=><div key={n}><span><i style={{background:colors[i]}}/>{n}</span><strong>{connected?s.device.values?.[i]??'—':'—'}</strong></div>)}</div>;
 const bars=<div className="finger-bars">{names.map((n,i)=><div key={n}><div className="bar-track"><span style={{height:connected?`${Math.min(100,Math.max(3,(s.device.values?.[i]||0)/30))}%`:'0%'}}/></div><small>{n}</small></div>)}</div>;
 const timeline=(points=[])=><div className="timeline">{points.length?points.map((p,i)=><span key={i} className={p.matched?'match':'adjust'} title={`${fmt(p.elapsed)} ${p.matched?'姿态匹配':'需要调整'}`}/>):<p>开始练习后，将记录每一次动作变化</p>}</div>;
 return <div className="desktop-app">
 <aside className="sidebar"><div className="brand"><FlowerLotus size={39} weight="light"/><h1>非遗之手</h1><p>陶艺教学工作台</p></div><nav>{sections.map(([id,name,Icon])=><button key={id} className={page===id?'selected':''} onClick={()=>{setPage(id);if(id==='settings')setSettings({...s.settings});}}><Icon size={25} weight={page===id?'fill':'regular'}/>{name}</button>)}</nav><div className="sidebar-bottom"><button onClick={openSettings}><UserCircle size={30} weight="duotone"/>教学人员<CaretRight/></button><button onClick={()=>setModal('help')}><Question size={23}/>帮助中心</button></div></aside>
 <main className="workspace"><header className="page-header"><div><h2>{sections.find(x=>x[0]===page)?.[1]}</h2><p>{page==='work'?'揉泥基础 · 感受手中的变化':page==='device'?'连接手套，让每一次动作被看见':page==='gestures'?'留下参考姿态，建立自己的练习标准':page==='history'?'回顾每一次练习，见证细小的进步':'让工作台适应你的使用习惯'}</p></div><div className="header-right"><div><Badge active={connected}>{connected?'手套已连接':'手套待连接'}</Badge><Badge active={s.peers.mobile}>{s.peers.mobile?'手机端已连接':'手机端待连接'}</Badge></div><small>{new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric'})}</small></div></header>
 {error&&<div className="notice error"><Info/>{error}</div>}
 {page==='work'&&<><div className="session-toolbar panel"><div className="toolbar-field"><FlowerLotus size={24}/><label>练习项目<select aria-label="练习项目"><option>揉泥基础</option></select></label></div><div className="toolbar-field"><UserCircle size={24}/><label>校准档案<button className="text-button" onClick={()=>setPage('device')}>{calibrated?s.calibration.learner:'尚未校准'}<CaretRight/></button></label></div><div className="session-time"><Clock size={25}/><span>{s.session?(s.session.paused?'已暂停':'练习中'):'准备就绪'}</span><strong>{fmt(s.session?.elapsed)}</strong></div><div className="button-row">{s.session?<><button disabled={busy} onClick={()=>act(s.session.paused?'resume':'pause')}>{s.session.paused?'继续练习':'暂停练习'}</button><button className="primary" disabled={busy} onClick={finish}>结束并生成报告</button></>:<button className="primary" disabled={busy} onClick={()=>act('start')}><Play weight="fill"/>开始练习</button>}</div></div>
 <div className="work-grid"><div className="work-left"><section className="panel chart-panel"><div className="panel-heading"><h3>手指传感数据</h3><div className="button-row"><select aria-label="曲线时间范围" value={range} onChange={e=>setRange(Number(e.target.value))}><option value={20}>最近20秒</option><option value={60}>最近60秒</option></select><button className="small" disabled={!s.samples.length} onClick={csv}><DownloadSimple/>导出数据</button></div></div><div className="legend">{names.map((n,i)=><span key={n}><i style={{background:colors[i]}}/>{n}</span>)}</div><SensorChart samples={s.samples} seconds={range}/>{readings}</section>
 <section className="panel session-panel"><h3>本次练习</h3><div className="metrics"><div><Clock/><span>练习时长<strong>{fmt(s.session?.elapsed)}</strong></span></div><div><Waveform/><span>采集帧数<strong>{s.session?.sampleCount||0}<small> 帧</small></strong></span></div><div><CheckCircle/><span>匹配次数<strong>{s.session?.matches||0}<small> 次</small></strong></span></div></div>{timeline(s.session?s.samples.filter((_,i)=>i%Math.max(1,Math.ceil(s.samples.length/50))===0):[])}<div className="timeline-labels"><span>00:00</span><span>{fmt(s.session?.elapsed)}</span><span><i className="green-dot"/>姿态匹配 <i className="orange-dot"/>需要调整</span></div><h4>最近事件</h4><div className="events">{s.events.length?s.events.slice(0,2).map(e=><div key={e.id}><time>{fmt(e.elapsed)}</time><i className={e.kind==='adjust'?'orange-dot':'green-dot'}/>{e.text}</div>):<div className="muted">准备好后开始练习，过程会自动记录。</div>}</div></section></div>
 <div className="work-right"><section className="panel video-panel"><div className="panel-heading"><h3>动作示范</h3><select aria-label="示范角度" value={videoIndex} onChange={e=>setVideoIndex(+e.target.value)}><option value={0}>正面</option><option value={1}>侧面</option><option value={2}>近景</option></select></div><video key={videoIndex} controls playsInline poster={ART+'pottery-hands.png'} src={API+`/media/lesson-${videoIndex}.mp4`} preload="metadata"/><p>揉泥基础 · 参考视频</p></section><section className="panel feedback-panel"><h3>当前反馈</h3><div className="feedback-main"><span className={'feedback-icon '+(feed.kind==='match'?'':'neutral')}><Check size={32}/></span><div><h2>{feed.text}</h2><p>{feed.kind==='match'?'手指状态与已录入参考姿态接近':feed.kind==='adjust'?'请调整手指姿态，慢慢找到熟悉的感觉':connected?'录入一个参考姿态，开始动作比较':'连接手套，获取动作反馈'}</p></div></div><div className="feedback-detail"><span>匹配模板<strong>{feed.template||'—'}</strong></span><button className="voice" aria-pressed={s.settings.voice} onClick={()=>act('settings',{voice:!s.settings.voice})}><SpeakerHigh/>语音提示<span className={'toggle '+(s.settings.voice?'on':'')}/></button></div></section><section className="panel quick-panel"><h3>设备快捷操作</h3><div className="quick-body"><img src={ART+'glove-open.png'} alt="陶艺手套"/><div><strong>陶艺手套 · {connected?(s.device.source==='serial'?'串口连接':s.device.source==='file'?'记录回放':'蓝牙连接'):'待连接'}</strong><div className="quick-actions"><button onClick={()=>setCalibrationOpen(true)}><ArrowClockwise/>重新校准</button><button onClick={()=>setPage('gestures')}><Hand/>管理手势</button><button onClick={()=>setPage('device')}><Gear/>查看设备</button></div><p className="hint"><Info/>更换佩戴者后请重新校准</p></div></div></section></div></div></>}
 {page==='device'&&<HardwarePanel hardware={s.hardware} session={s.session}/>}
 {page==='device'&&<div className="device-grid"><section className="panel device-overview"><img className="glove-hero" src={ART+'glove-open.png'} alt="五指陶艺传感手套"/><h3>陶艺手套</h3><Badge active={connected}>{connected?'数据接收正常':'等待设备连接'}</Badge>{bars}<div className="button-row"><button className="primary" disabled={busy} onClick={()=>run(async()=>{document.getElementById('hardware-panel')?.scrollIntoView({behavior:'smooth'});setToast('请在真实手套接入面板选择串口');})}><PlugsConnected/>串口连接</button><button onClick={()=>{document.getElementById('hardware-panel')?.scrollIntoView({behavior:'smooth'});setToast('请在上方点击扫描蓝牙手套');}}><Bluetooth/>蓝牙连接</button></div>{connected&&<button className="danger-link" onClick={()=>run(disconnect)}>断开连接</button>}<p className="muted">连接后，手指状态将随你的动作变化。</p></section><section className="panel calibration"><div className="panel-heading"><h3>软件个人参考</h3><Badge active={calibrated}>{calibrated?'已完成':'待校准'}</Badge></div><p className="muted">这里保存软件端参考。手套标定请使用上方真实手套面板。</p><div className="calibration-steps"><div className="done">1 <span>佩戴检查</span></div><div className={s.calibration?.fist?'done':''}>2 <span>握拳</span></div><div className={calibrated?'done':''}>3 <span>张开</span></div></div><img className="fist-hero" src={ART+(s.calibration?.fist&&!calibrated?'glove-open.png':'glove-fist.png')} alt="手套校准姿态"/><h3>{s.calibration?.fist&&!calibrated?'张开五指，保持稳定':'轻轻握拳，保持稳定'}</h3><div className="button-row"><button className="primary" disabled={busy} onClick={()=>act('calibrate',{step:s.calibration?.fist&&!calibrated?'open':'fist'},'姿态已采集')}>{s.calibration?.fist&&!calibrated?'采集张开姿态':'采集握拳姿态'}</button><button onClick={()=>setPage('gestures')}>管理参考手势<ArrowRight/></button></div></section></div>}
 {page==='gestures'&&<section className="panel gestures-panel"><div className="panel-heading"><div><h3>我的参考手势</h3><p className="muted">以当前手指采样值录入姿态，用于本地匹配。</p></div><div className="button-row"><button onClick={()=>{inputRef.current.accept='.json';inputRef.current.dataset.mode='templates';inputRef.current.click();}}><UploadSimple/>导入</button><button onClick={()=>download('参考手势.json',JSON.stringify({templates:s.templates},null,2))}><DownloadSimple/>导出</button><button className="primary" onClick={()=>{setForm({name:'',kind:'correct',tolerance:s.settings.tolerance});setModal('gesture');}}><Hand/>录入手势</button></div></div>{s.templates.length?<div className="gesture-grid">{s.templates.map(t=><article className="gesture-card" key={t.id}><div><Badge active={t.kind==='correct'}>{t.kind==='correct'?'正确姿态':'待纠正姿态'}</Badge><button className="icon-button" aria-label={'删除'+t.name} onClick={()=>setModal({deleteTemplate:t})}><Trash/></button></div><Hand size={48} weight="duotone"/><h3>{t.name}</h3><p>揉泥基础 · 容差 {t.tolerance}</p><div className="template-values">{t.values.map((v,i)=><span key={i}>{names[i]}<b>{v}</b></span>)}</div></article>)}</div>:<div className="empty"><Hand size={60} weight="duotone"/><h3>从第一个参考姿态开始</h3><p>连接手套，保持一个清晰的动作，再点击“录入手势”。</p></div>}</section>}
 {page==='history'&&<section className="panel history-panel"><div className="panel-heading"><div><h3>练习记录</h3><p className="muted">共 {s.reports.length} 次练习</p></div><input aria-label="搜索练习记录" placeholder="搜索项目或学习者" value={search} onChange={e=>setSearch(e.target.value)}/></div>{s.reports.length?<table><thead><tr><th>练习项目</th><th>学习者</th><th>时间</th><th>时长</th><th>姿态匹配</th><th>操作</th></tr></thead><tbody>{s.reports.filter(r=>(r.lesson+r.learner).includes(search)).map(r=><tr key={r.id}><td><div className="lesson-cell"><img src={ART+'pottery-hands.png'} alt="揉泥"/><b>{r.lesson}</b></div></td><td>{r.learner}</td><td>{date(r.startedAt)}</td><td>{fmt(r.duration)}</td><td>{r.sampleCount?`${r.matches}次`:'未采集手套数据'}</td><td><button className="text-button" onClick={()=>{setReport(r);setModal('report');}}>查看报告<CaretRight/></button></td></tr>)}</tbody></table>:<div className="empty"><FileText size={60} weight="duotone"/><h3>每一次练习，都值得留下</h3><p>完成一次练习后，报告会保存在这里。</p><button className="primary" onClick={()=>setPage('work')}>开始第一次练习</button></div>}</section>}
 {page==='settings'&&settings&&<div className="settings-grid"><section className="panel"><h3>学习与声音</h3><label className="field">学习者名称<input value={settings.learner} onChange={e=>setSettings({...settings,learner:e.target.value})}/></label><label className="check-row"><span><SpeakerHigh/>语音提示</span><input type="checkbox" checked={settings.voice} onChange={e=>setSettings({...settings,voice:e.target.checked})}/></label><label className="field">默认匹配容差<input type="number" min="1" max="5000" value={settings.tolerance} onChange={e=>setSettings({...settings,tolerance:+e.target.value})}/></label><button className="primary" onClick={()=>act('settings',settings,'设置已保存')}>保存设置</button><hr/><h3>两端协同</h3><p className="muted">手机端与工作台连接同一服务，共享练习进度和历史记录。</p><a className="link-button" href={API+'/mobile/'} target="_blank">打开手机端<DeviceMobile/></a><button onClick={()=>run(async()=>{const n=await request('/api/network');setToast('局域网服务地址：'+n.ips.map(ip=>`http://${ip}:${n.port}`).join('、'));})}>查看局域网地址</button></section><section className="panel"><h3>其他设备连接设置</h3><p className="muted">当前手套由电脑服务以9600连接；下面的设置用于其他设备，暂不适用于本次手套接入。</p><label className="field">串口波特率<select value={settings.baudRate} onChange={e=>setSettings({...settings,baudRate:+e.target.value})}>{[9600,19200,38400,57600,115200,230400].map(v=><option key={v}>{v}</option>)}</select></label>{[['serviceUUID','蓝牙服务 UUID'],['notifyUUID','通知特征 UUID'],['writeUUID','写入特征 UUID']].map(([k,label])=><label className="field" key={k}>{label}<input value={settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.value})} placeholder="填写设备提供的 UUID"/></label>)}<button className="primary" onClick={()=>act('settings',settings,'连接设置已保存')}>保存连接设置</button><hr/><h3>设备指令</h3><div className="button-row"><input aria-label="设备指令" value={cmd} onChange={e=>setCmd(e.target.value)} placeholder="例如 HELP"/><button onClick={()=>run(async()=>{const result=await sendCommand(cmd);setToast('设备已确认：'+result.reply);})}>发送</button></div><hr/><h3>数据记录</h3><button onClick={()=>{inputRef.current.accept='.csv,.txt';inputRef.current.dataset.mode='data';inputRef.current.click();}}><UploadSimple/>打开采样记录</button><p className="muted">读取五列传感器数值的 CSV 文件，按原始记录回放。</p><button onClick={()=>{clearInterval(replayRef.current);act('disconnect');setToast('记录回放已停止');}}>停止回放</button></section></div>}
 <footer className="status-footer"><span><i className={connected?'green-dot':'gray-dot'}/>{connected?'数据接收正常':'等待手套连接'}</span><span>记录自动保存</span><span className="footer-brand">以手传艺 · 感知匠心</span></footer>
 </main>
 {calibrationOpen&&<CalibrationDialog state={s} error={error} onClose={()=>setCalibrationOpen(false)}/>}
 <input hidden ref={inputRef} type="file" onChange={e=>run(async()=>{const f=e.target.files?.[0];if(!f)return;const text=await f.text();if(e.target.dataset.mode==='templates'){await action('importTemplates',JSON.parse(text));setToast('参考手势已导入');}else{const rows=text.split(/\r?\n/).map(l=>{const a=l.trim().split(',');return parseValues(a.length===6?a.slice(1).join(','):l);}).filter(Boolean);if(!rows.length)throw Error('未找到有效的五路采样记录');if(s.session)throw Error('请先结束当前练习，再打开采样记录');clearInterval(replayRef.current);await action('start');let i=0;replayRef.current=setInterval(async()=>{if(i>=rows.length){clearInterval(replayRef.current);setToast('采样记录已回放完毕，可生成报告');return;}try{await request('/api/sample',{values:rows[i++],name:f.name,source:'file'});}catch(e){clearInterval(replayRef.current);setToast(e.message);}},150);setPage('work');}e.target.value='';})}/>
 {toast&&<div className="toast" role="status"><Info size={21}/>{toast}<button className="icon-button" onClick={()=>setToast('')} aria-label="关闭提示"><X/></button></div>}
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section className={'modal '+(modal==='report'?'report-modal':'')} role="dialog" aria-modal="true" aria-label={modal==='report'?'学习报告':modal==='gesture'?'录入手势':'提示'} onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" aria-label="关闭" onClick={()=>setModal(null)}><X size={24}/></button>
 {modal==='gesture'&&<><h2>录入参考手势</h2><p className="muted">戴好手套，保持需要录入的姿态。</p><label className="field">手势名称<input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="例如 揉泥准备姿态"/></label><label className="field">姿态类型<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}><option value="correct">正确姿态</option><option value="incorrect">待纠正姿态</option></select></label><label className="field">匹配容差<input type="number" value={form.tolerance} onChange={e=>setForm({...form,tolerance:+e.target.value})}/></label>{readings}<button className="primary full" disabled={busy} onClick={()=>run(async()=>{await action('template',form);setModal(null);setToast('参考手势已保存');})}>采集并保存</button></>}
 {modal?.deleteTemplate&&<><h2>删除参考手势？</h2><p>将移除“{modal.deleteTemplate.name}”，你可以重新录入。</p><button onClick={()=>run(async()=>{await action('deleteTemplate',{id:modal.deleteTemplate.id});setModal(null);})}>确认删除</button></>}
 {modal==='help'&&<><h2>从一次揉泥开始</h2><ol className="help-list"><li><b>连接设备</b><p>在“设备与校准”中选择连接方式。收到五路采样后显示已连接。</p></li><li><b>完成校准与参考录入</b><p>先握拳、再张开，进入手势管理录入自己的参考姿态。</p></li><li><b>观察示范，开始练习</b><p>选择视频角度，按自己的节奏练习。结束后查看报告。</p></li></ol><p className="hint">未连接手套时，可以观看示范并记录自主练习时长。</p></>}
 {modal==='report'&&report&&<><div className="report-title"><FlowerLotus size={35}/><p>非遗之手 · 学习报告</p><h2>这一次，更从容</h2><span>{report.lesson} · {date(report.startedAt)}</span></div><div className="metrics"><div><Clock/><span>练习时长<strong>{fmt(report.duration)}</strong></span></div><div><Waveform/><span>采集帧数<strong>{report.sampleCount}</strong></span></div><div><CheckCircle/><span>匹配次数<strong>{report.sampleCount?report.matches:'—'}</strong></span></div></div><h3>姿态匹配记录</h3>{report.sampleCount?timeline(report.timeline):<p className="notice">本次没有连续五指采样，已保存练习时长。硬件识别事件 {report.hardwareEventCount||0} 条，详见原始日志。</p>}<div className="report-advice"><Lightbulb/><div><h4>练习建议</h4><p>先放慢节奏，再保持连贯。</p><p>重新佩戴手套后，记得校准。</p></div></div><div className="button-row"><button className="primary" onClick={()=>{setModal(null);setPage('work');}}>再练一次</button><button onClick={()=>download('学习报告-'+report.id+'.json',JSON.stringify(report,null,2))}><DownloadSimple/>导出报告</button>{report.rawLog&&<a className="link-button" href={API+'/api/session-log?id='+report.id}>导出原始日志</a>}<button onClick={()=>window.print()}>打印</button></div></>}
 </section></div>}
 </div>;
}

