import {useEffect,useState} from 'react';
export const API=import.meta.env.VITE_API_ORIGIN||`${location.protocol}//${location.hostname}:4180`,ART='/art/';
export const names=['拇指','食指','中指','无名指','小指'],colors=['#c56a46','#dca24b','#4f886d','#6797b6','#a280ac'];
export const fmt=(s=0)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
export const date=t=>new Date(t).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'});
export async function request(path,body){const r=await fetch(API+path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(path.startsWith('/api/hardware/')?30000:5000)});const d=await r.json();if(!r.ok)throw Error(d.error||'操作失败');return d;}
export const action=(type,payload={})=>request('/api/action',{type,payload});
export function useStudio(client){const[s,set]=useState(null),[error,se]=useState('');useEffect(()=>{let live=true,busy=false;async function poll(){if(busy)return;busy=true;try{const d=await request('/api/state?client='+client);if(live){set(d);se('');}}catch{if(live)se('暂时无法连接工作台，请检查服务是否启动');}finally{busy=false;}}poll();const t=setInterval(poll,600);return()=>{live=false;clearInterval(t);};},[client]);return[s,error];}
export function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);}
export function parseValues(line){try{const j=JSON.parse(line),v=Array.isArray(j)?j:j.values;if(Array.isArray(v)&&v.length===5&&v.every(n=>typeof n==='number'&&Number.isFinite(n)&&n>=0&&n<=65535))return v;}catch{}const a=line.trim().split(',');if(a.length!==5||a.some(s=>!s.trim()))return null;const v=a.map(Number);return v.every(n=>Number.isFinite(n)&&n>=0&&n<=65535)?v:null;}
let port=null,reader=null,ble=null,writeChar=null,running=false,pending='',lastSend=0;
async function forward(values,source){if(Date.now()-lastSend<100)return;lastSend=Date.now();await request('/api/sample',{values,name:'陶艺手套',source});}
export async function disconnect(){running=false;if(reader)await reader.cancel().catch(()=>{});if(port){await port.close().catch(()=>{});port=null;}if(ble?.gatt?.connected)ble.gatt.disconnect();ble=null;writeChar=null;await action('disconnect');}
export async function connectSerial(baudRate=115200,onError=()=>{}){if(!navigator.serial)throw Error('此浏览器不支持串口，请在 Chrome 或 Edge 中打开工作台连接手套');if(port)await disconnect();port=await navigator.serial.requestPort();await port.open({baudRate});running=true;reader=port.readable.getReader();pending='';(async()=>{try{while(running){const{value,done}=await reader.read();if(done)break;pending+=new TextDecoder().decode(value);const lines=pending.split(/\r?\n/);pending=lines.pop()||'';if(pending.length>65536)pending='';for(const l of lines){const v=parseValues(l);if(v)await forward(v,'serial');}}}catch(e){if(running)onError('设备连接已中断：'+e.message);}finally{reader?.releaseLock();reader=null;running=false;await action('disconnect').catch(()=>{});}})();}
export async function connectBLE(settings,onError=()=>{}){if(!navigator.bluetooth)throw Error('此浏览器不支持蓝牙，请使用 Chrome、Edge 或微信小程序');if(!settings.serviceUUID||!settings.notifyUUID)throw Error('请先填写设备的蓝牙服务与通知特征 UUID');ble=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[settings.serviceUUID]});ble.addEventListener('gattserverdisconnected',()=>{action('disconnect').catch(()=>{});onError('蓝牙连接已断开');});const g=await ble.gatt.connect(),svc=await g.getPrimaryService(settings.serviceUUID),ch=await svc.getCharacteristic(settings.notifyUUID);if(settings.writeUUID)writeChar=await svc.getCharacteristic(settings.writeUUID);pending='';ch.addEventListener('characteristicvaluechanged',e=>{pending+=new TextDecoder().decode(e.target.value);const lines=pending.split(/\r?\n/);pending=lines.pop()||'';if(parseValues(pending)){lines.push(pending);pending='';}if(pending.length>65536)pending='';for(const l of lines){const v=parseValues(l);if(v)forward(v,'ble').catch(e=>onError(e.message));}});await ch.startNotifications();}
export async function sendCommand(command){if(!command.trim())throw Error('请填写指令');return request('/api/hardware/command',{command});}
