import test from 'node:test';
import assert from 'node:assert/strict';
import {Studio,parseSample} from '../core.mjs';
test('parser accepts five-channel CSV and JSON, rejects malformed packets',()=>{assert.deepEqual(parseSample('1,2,3,4,5'),[1,2,3,4,5]);assert.deepEqual(parseSample('{"values":[1,2,3,4,5]}'),[1,2,3,4,5]);for(const s of ['1,2,3','1,,3,4,5','1,2,3,4,-1','1,2,3,4,NaN','{"values":[1,2,3,4,"5"]}','ERR: mask=0'])assert.equal(parseSample(s),null);});
test('session duration excludes pause and preserves honest no-data report',()=>{let now=10000;const s=new Studio(undefined,()=>now);s.action('start');now+=5000;s.action('pause');now+=20000;assert.equal(s.elapsed(),5);s.action('resume');now+=7000;const r=s.action('finish');assert.equal(r.duration,12);assert.equal(r.ratio,null);assert.equal(r.matches,0);assert.equal(s.session,null);assert.equal(s.data.reports.length,1);});
test('calibration requires live device and each finger range',()=>{let now=10000;const s=new Studio(undefined,()=>now);assert.throws(()=>s.action('calibrate',{step:'fist'}));s.ingest([100,100,100,100,100]);s.action('calibrate',{step:'fist'});s.ingest([100,200,200,200,200]);assert.throws(()=>s.action('calibrate',{step:'open'}));s.ingest([200,200,200,200,200]);s.action('calibrate',{step:'open'});assert.equal(s.data.calibration.completed,true);now+=4000;assert.equal(s.state().device.connected,false);assert.throws(()=>s.action('template',{name:'姿态'}));});
test('held matching pose counts once, pause and stale data cannot inflate result',()=>{let now=10000;const s=new Studio(undefined,()=>now);s.ingest([100,200,300,400,500]);s.action('template',{name:'参考',tolerance:20});s.action('start');s.ingest([100,200,300,400,500]);now+=1100;s.ingest([102,200,300,400,500]);assert.equal(s.session.matches,1);now+=500;s.ingest([100,200,300,400,500]);assert.equal(s.session.matches,1);s.action('pause');const frames=s.session.sampleCount;now+=1000;s.ingest([100,200,300,400,500]);assert.equal(s.session.sampleCount,frames);s.action('resume');s.ingest([100,200,300,400,500]);now+=4000;s.ingest([100,200,300,400,500]);assert.equal(s.session.matches,1);});
test('template import validates all entries before mutation',()=>{const s=new Studio();assert.throws(()=>s.action('importTemplates',{templates:[{name:'x',values:[1,2],kind:'correct',tolerance:10}]}));assert.equal(s.data.templates.length,0);});
test('reports survive reconstruction without stale connected status',()=>{let now=10000;const s=new Studio(undefined,()=>now);s.action('start');now+=2000;s.action('finish');const next=new Studio(JSON.parse(JSON.stringify(s.data)));assert.equal(next.data.reports.length,1);assert.equal(next.state().device.connected,false);assert.equal(next.session,null);});
