import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import fs from 'node:fs';import path from 'node:path';
const require=createRequire(import.meta.url);
test('native page executes offline training, saves report and restores it',async()=>{let config,storage={};globalThis.wx={getStorageSync:k=>storage[k],setStorageSync:(k,v)=>storage[k]=v,setNavigationBarTitle:()=>{},showToast:()=>{},request:()=>{throw Error('offline must not request network');}};globalThis.Page=c=>config=c;require('../miniprogram/pages/index/index.js');const page={...config,data:structuredClone(config.data),setData(obj){Object.assign(this.data,obj);}};page.onLoad();await new Promise(r=>setTimeout(r,1));assert.equal(page.data.s.reports.length,0);await page.action('start');const r=await page.action('finish');assert.equal(r.sampleCount,0);assert.equal(r.ratio,null);await page.refresh();assert.equal(page.data.s.reports.length,1);page.showReport(r);assert.equal(page.data.page,'report');assert.equal(storage['pottery-data'].reports.length,1);});
test('native assets and declared entry pages exist',()=>{const root=path.resolve('miniprogram');const app=JSON.parse(fs.readFileSync(path.join(root,'app.json')));for(const p of app.pages)for(const ext of ['.js','.wxml','.wxss','.json'])assert.ok(fs.existsSync(path.join(root,p+ext)));const wxml=fs.readFileSync(path.join(root,'pages/index/index.wxml'),'utf8');for(const m of wxml.matchAll(/src="(\/assets\/[^"{]+)"/g))assert.ok(fs.existsSync(path.join(root,m[1])),m[1]);});
test('native auxiliary device commands go to host and do not start phone BLE',async()=>{
 let config;const calls=[];globalThis.Page=c=>config=c;globalThis.wx={showToast:()=>{},openBluetoothAdapter:()=>{throw Error('Host mode must not open phone BLE');}};
 delete require.cache[require.resolve('../miniprogram/pages/index/index.js')];require('../miniprogram/pages/index/index.js');
 const page={...config,base:'http://host:4180',data:structuredClone(config.data),setData(p){Object.assign(this.data,p);},remote:async(path,body)=>{calls.push({path,body});return {reply:'MODE:0'};},refresh:async()=>{}};
 let completion;page.perform=fn=>{completion=fn();return completion;};page.hardwareCommand({currentTarget:{dataset:{command:'MODE 0'}}});await completion;
 assert.deepEqual(calls,[{path:'/api/hardware/command',body:{command:'MODE 0'}}]);await page.connect();assert.equal(calls.length,1);
});
